version: '3.3'

services:
  php_apache:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
    - ./portfolio:/var/www/html/
    ports:
    - 8000:80

  nginx:
    image: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes:
      - ./nginx/index.php:/usr/share/nginx/html/index.php
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:80
    depends_on:
      - web_php

  web_php:
    image: php:fpm-alpine
    volumes:
      - ./nginx/:/usr/share/nginx/html

  mysql:
    image: mysql
    command: "--innodb_use_native_aio=0"
    volumes:
      - "./db_data:/var/lib/mysql"
      - "./mysqlconf:/etc/mysql/conf.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql